service: rails-function 

provider:
  name: aws
  runtime: ruby2.5
  region: eu-west-2

functions:
  hello:
    handler: lambda.handler
    events:
      - http:
          path: /{path+}
          method: get        
      - http:
          path: /{path+}
          method: post        
      - http:
          path: /{path+}
          method: put
      - http:
          path: /{path+}
          method: delete
    environment:
      RAILS_ENV: production
package:
  include:
    - ./lambda.rb
    - ./app/**
    - ./bin/**
    - ./config/**
    - ./lib/**
    - ./public/**
    - ./.bundle/**
    - ./Gemfile
    - ./Gemfile.lock

plugins:
  - serverless-ruby-package
